AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AMI:
    Type: String
  InstanceProfile:
    Type: String
  InstanceType:
    Type: String
  SubnetsId:
    Type: CommaDelimitedList
  AvailabilityZones:
    Type: CommaDelimitedList
Resources:
  LaunchTemplateSimple:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !Ref InstanceProfile
        ImageId: !Ref AMI
        InstanceMarketOptions:
          MarketType: spot
        InstanceType: !Ref InstanceType
        CreditSpecification:
          CpuCredits: standard
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: "Ec2AutoScalingDemo"
      VersionDescription: "Init Version"

  AutoscalingGroupSimple:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-Simple
      AvailabilityZones:
        - !Select [ 0, !Ref AvailabilityZones ]
        - !Select [ 1, !Ref AvailabilityZones ]
      CapacityRebalance: True
      Cooldown: 300
      DefaultInstanceWarmup: 300
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateSimple
        Version: !GetAtt LaunchTemplateSimple.LatestVersion
      MaxSize: 2
      MinSize: 1
      VPCZoneIdentifier:
        - !Select [0, !Ref SubnetsId]
        - !Select [1, !Ref SubnetsId]

  AutoscaleCPUAlarmScaleOut:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "SimpleScaling-CPUAlarmScaleOut"
      AlarmDescription: "Alarm when CPU exceeds 50%"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoscalingGroupSimple
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 3
      Threshold: 50
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AutoScalingPolicyScaleOut
      TreatMissingData: "notBreaching"

  AutoscaleCPUAlarmScaleIn:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "SimpleScaling-CPUAlarmScaleIn"
      AlarmDescription: "Alarm when CPU below 50%"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoscalingGroupSimple
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 3
      Threshold: 50
      ComparisonOperator: "LessThanThreshold"
      AlarmActions:
        - !Ref AutoScalingPolicyScaleIn
      TreatMissingData: "notBreaching"

  AutoScalingPolicyScaleOut:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ExactCapacity
      AutoScalingGroupName: !Ref AutoscalingGroupSimple
      PolicyType: SimpleScaling
      ScalingAdjustment: '2'

  AutoScalingPolicyScaleIn:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ExactCapacity
      AutoScalingGroupName: !Ref AutoscalingGroupSimple
      PolicyType: SimpleScaling
      ScalingAdjustment: '1'