AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AMI:
    Type: String
  InstanceProfile:
    Type: String
  InstanceType:
    Type: String
  SubnetsId:
    Type: CommaDelimitedList
  AvailabilityZones:
    Type: CommaDelimitedList
Resources:
  LaunchTemplateStep:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !Ref InstanceProfile
        ImageId: !Ref AMI
        InstanceMarketOptions:
          MarketType: spot
        InstanceType: !Ref InstanceType
        CreditSpecification:
          CpuCredits: standard
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: "Ec2AutoScalingDemo"
      VersionDescription: "Init Version"

  AutoscalingGroupStep:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-Step
      AvailabilityZones:
        - !Select [ 0, !Ref AvailabilityZones ]
        - !Select [ 1, !Ref AvailabilityZones ]
      CapacityRebalance: True
      Cooldown: 300
      DefaultInstanceWarmup: 300
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateStep
        Version: !GetAtt LaunchTemplateStep.LatestVersion
      MaxSize: 4
      MinSize: 1
      VPCZoneIdentifier:
        - !Select [0, !Ref SubnetsId]
        - !Select [1, !Ref SubnetsId]

  AverageAutoscaleCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "StepScaling-AverageCPUAlarm"
      AlarmDescription: "Alarm AvgCPUUtilization"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoscalingGroupStep
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 3
      Threshold: 25
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AutoScalingPolicyStep
      OKActions:
        - !Ref AutoScalingPolicyStep
      TreatMissingData: "notBreaching"

  AutoScalingPolicyStep:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ExactCapacity
      AutoScalingGroupName: !Ref AutoscalingGroupStep
      MetricAggregationType: Average
      PolicyType: StepScaling
      StepAdjustments:
        - MetricIntervalLowerBound: '0'
          MetricIntervalUpperBound: '20'
          ScalingAdjustment: '2'
        - MetricIntervalLowerBound: '20'
          MetricIntervalUpperBound: '40'
          ScalingAdjustment: '3'
        - MetricIntervalLowerBound: '40'
          ScalingAdjustment: '4'